### ISSUE TITLE
panic: open ./font/gloriahallelujah.ttf: no such file or directory

### ISSUE THREAD

**Issue by timhughes** [esimov/diagram#3]
Great tool :-)

There is a crash if you are not running the tool from the root of the git checkout because the font isnt there.

You may be able to embed the font using something like https://github.com/jteeuwen/go-bindata

```
thughes@titanium [0] $ diagram
panic: open ./font/gloriahallelujah.ttf: no such file or directory

goroutine 1 [running, locked to thread]:
github.com/esimov/diagram/canvas.NewCanvas(0xc4203c9900, 0x6e400f, 0x1b, 0x4008000000000000, 0x1)
	/home/thughes/go/src/github.com/esimov/diagram/canvas/canvas.go:25 +0x125
github.com/esimov/diagram/canvas.DrawDiagram(0xc4203b28a0, 0x5d, 0xc420406540, 0x1f, 0xa, 0xc420406540)
	/home/thughes/go/src/github.com/esimov/diagram/canvas/generator.go:336 +0x238
github.com/esimov/diagram/ui.(*UI).drawDiagram(0xc42007a480, 0x6d5d9c, 0x7, 0xc420055e6c, 0x2)
	/home/thughes/go/src/github.com/esimov/diagram/ui/panels.go:459 +0x2f4
github.com/esimov/diagram/ui.onDrawDiagram.func1(0xc420104000, 0xc4201162d0, 0xc420055cc0, 0x510d67)
	/home/thughes/go/src/github.com/esimov/diagram/ui/handlers.go:65 +0x3f
github.com/jroimartin/gocui.(*Gui).execKeybindings(0xc420104000, 0xc4201162d0, 0xc420055d70, 0xc420055d28, 0x48be40, 0xc420055e08)
	/home/thughes/go/src/github.com/jroimartin/gocui/gui.go:629 +0xe6
github.com/jroimartin/gocui.(*Gui).onKey(0xc420104000, 0xc420055d70, 0x51a577, 0x18)
	/home/thughes/go/src/github.com/jroimartin/gocui/gui.go:593 +0x1d4
github.com/jroimartin/gocui.(*Gui).handleEvent(0xc420104000, 0xc420055d70, 0xc420055d68, 0x1)
	/home/thughes/go/src/github.com/jroimartin/gocui/gui.go:413 +0x40
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc420104000, 0xc420055ec8, 0x5d8a43)
	/home/thughes/go/src/github.com/jroimartin/gocui/gui.go:373 +0x1ac
github.com/esimov/diagram/ui.(*UI).Loop(0xc42007a480)
	/home/thughes/go/src/github.com/esimov/diagram/ui/ui.go:66 +0x32
github.com/esimov/diagram/ui.InitApp()
	/home/thughes/go/src/github.com/esimov/diagram/ui/app.go:10 +0x68
main.main()
	/home/thughes/go/src/github.com/esimov/diagram/main.go:37 +0x1ee
```

**Comment by esimov** [comment]
Resolved by this pull request: https://github.com/esimov/diagram/pull/4
